name: PlantUML Diagrams

on:
  push:
    branches:
      - main
      - warmhouse
  pull_request:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          java-package: 'jdk'

      - name: Install latest PlantUML + Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz wget
          wget -O plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2024.6/plantuml-1.2024.6.jar

      - name: Generate Diagrams
        run: |
          java -jar plantuml.jar schemas/*.puml

      - name: Commit generated diagrams
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add schemas/*.png || true
          if git diff --cached --quiet; then
          echo "No diagram changes to commit."
          exit 0
          fi
          git commit -m "Automated diagram generation"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Automated diagram generation"
          branch: ci/diagrams/${{ github.ref_name }}
          title: "Automated PlantUML diagram generation"
          body: "This PR contains updated PlantUML diagrams (PNG & SVG) generated by GitHub Actions."
          labels: diagrams, automation
          delete-branch: true